### PR TITLE
#4: Enable to specify version

### LINKED ISSUE #4: Wrong result when specify version
## Expected Behavior

```bash
$ npm-add-dependencies bulma@0.7.0
```

package.json

```js
{
  "name": "npm-add-dependencies-test",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "bulma": "0.7.0"
  }
}
```

## Actual Behavior

```bash
$ npm-add-dependencies bulma@0.7.0
```

package.json

```json
{
  "name": "npm-add-dependencies-test",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "bulma@0.7.0": "^0.7.5"
  }
}
```

## Specifications

  - Version: v0.1.5

### PR DESCRIPTION
**Pull request by 17number**
Fixes #4

## Proposed Changes

  - enable `npm-add-dependencies <package>@<version>`

### Note

Not support 'version range'(e.g. `npm install sax@">=0.1.0 <0.2.0"`) currently.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -56,16 +56,31 @@ class NpmAddDependencies {
...
+      npmRun.exec(`npm show ${dep} dist dist-tags`, (err, stdout) => {
         if (!err) {
           const parsed = stdout.match(/latest: '(.*?)'/i);
 
           if (!parsed || undefined === parsed[1]) {
-            console.error(`Could not obtain the latest version for: ${dep}. Skip.`);
+            if (!dep.includes('@')) {
+              console.error(`Could not obtain the latest version for: ${dep}. Skip.`);
+            } else {
+              const [depName, depVersion] = dep.split('@');
```
Comment (arfeo) [inline index.js]: What about moving this above, before `return` statement, so we could use it everywhere inside promise callback?

File: index.js [hunk 2]
```diff
@@ -56,16 +56,31 @@ class NpmAddDependencies {
...
   runNpmShow(dep) {
     return new Promise((resolve) => {
-      npmRun.exec(`npm show ${dep} dist-tags`, (err, stdout) => {
+      npmRun.exec(`npm show ${dep} dist dist-tags`, (err, stdout) => {
         if (!err) {
           const parsed = stdout.match(/latest: '(.*?)'/i);
 
           if (!parsed || undefined === parsed[1]) {
-            console.error(`Could not obtain the latest version for: ${dep}. Skip.`);
+            if (!dep.includes('@')) {
```
Comment (arfeo) [inline index.js]: If we do the thing from line 67's comment, here we can check for `undefined === depVersion`

File: index.js [hunk 3]
```diff
@@ -56,16 +56,31 @@ class NpmAddDependencies {
 
   runNpmShow(dep) {
     return new Promise((resolve) => {
-      npmRun.exec(`npm show ${dep} dist-tags`, (err, stdout) => {
+      npmRun.exec(`npm show ${dep} dist dist-tags`, (err, stdout) => {
```
Comment (arfeo) [inline index.js]: Why do you need the `dist` flag here?

File: index.js [hunk 4]
```diff
@@ -56,16 +56,31 @@ class NpmAddDependencies {
...
           } else {
-            this.result[dep] = `^${parsed[1]}`;
-
-            console.log(`Processed: ${dep}, latest version: ${parsed[1]}`);
+            if (!dep.includes('@')) {
+              this.result[dep] = `^${parsed[1]}`;
+              console.log(`Processed: ${dep}, latest version: ${parsed[1]}`);
+            } else {
+              const [depName, depVersion] = dep.split('@');
+              const parsed = stdout.match(/tarball: '(.*?)'/g);
```
Comment (arfeo) [inline index.js]: Why do you need it here?

**Review by arfeo — CHANGES_REQUESTED** [review]

**Comment by arfeo** [comment]
Have you also tested the script against `lodash@^4.17.0` and `lodash@~4.17.0`?

File: index.js (hunk 3 above)
Comment (17number) [reply index.js]: I thougt need the `dist` flag for exact version match, we could get only latest version with `dist-tags` flag.

```bash
$ npm show lodash@4.0.0 dist-tags
{ latest: '4.17.15' }

$ npm show lodash@4.0.0 dist dist-tags
dist =
{
  shasum: '9ac43844c595e28d30108b7ba583703395922dfc',
  tarball: 'https://registry.npmjs.org/lodash/-/lodash-4.0.0.tgz'
}
dist-tags = { latest: '4.17.15' }
```

But nothing will be displayed if specified version is not exist. I think over don't need `dist` flag.

```bash
$ npm show lodash@4.17.99 dist dist-tags

$
```

File: index.js (hunk 4 above)
Comment (17number) [reply index.js]: Please see [above comment](https://github.com/arfeo/npm-add-dependencies/pull/5#discussion_r314965697).

**Comment by 17number** [comment]
> Have you also tested the script against `lodash@^4.17.0` and `lodash@~4.17.0`?

This is `package.json` file after exec `npm-add-dependencies lodash@^4.0.0` and `npm-add-dependencies --dev lodash@^4.0.0`.

```diff
     "test": "echo \"Error: no test specified\" && exit 1"
   },
   "author": "",
-  "license": "ISC"
+  "license": "ISC",
+  "dependencies": {
+    "lodash": "^4.0.0"
+  },
+  "devDependencies": {
+    "lodash": "~4.0.0"
+  }
 }
```

File: index.js (hunk 1 above)
Comment (17number) [reply index.js]: Thank you for idea, I changed source code, please see [this commit](https://github.com/arfeo/npm-add-dependencies/pull/5/commits/4c13451a27f688b9c6800e8f400f880da318ad28).

File: index.js (hunk 2 above)
Comment (17number) [reply index.js]: Please see [above comment](https://github.com/arfeo/npm-add-dependencies/pull/5#discussion_r314966075)

**Comment by 17number** [comment]
> ### Note
> Not support 'version range'(e.g. `npm install sax@">=0.1.0 <0.2.0"`) currently.

I think to change [this code](https://github.com/arfeo/npm-add-dependencies/pull/5/commits/4c13451a27f688b9c6800e8f400f880da318ad28#diff-168726dbe96b3ce427e7fedce31bb0bcR60) to below, we can support version range.

```diff
   runNpmShow(dep) {
     const [depName, depVersion] = dep.split('@');
+    const depForShow = undefined === depVersion ? dep : `${depName}@"${depVersion}"`;
     return new Promise((resolve) => {
-      npmRun.exec(`npm show ${dep} dist-tags`, (err, stdout) => {
+      npmRun.exec(`npm show ${depForShow} dist-tags`, (err, stdout) => {
```

Example.

```bash
$ npm-add-dependencies lodash@">=4.2.0 <4.3.0"
This script adds dependencies (latest versions) into the package.json file without installing them

Adding dependencies to 'dependencies'...
Processed: lodash, specified version: >=4.2.0 <4.3.0
Done.
```

```diff
     "test": "echo \"Error: no test specified\" && exit 1"
   },
   "author": "",
-  "license": "ISC"
+  "license": "ISC",
+  "dependencies": {
+    "lodash": ">=4.2.0 <4.3.0"
+  }
 }
```

Could I include that change to this PR?

**Comment by arfeo** [comment]
Why?

```const depForShow = undefined === depVersion ? dep : `${depName}@"${depVersion}"`;```

`depForShow` will always be === `dep`.

image

File: index.js [hunk 5]
```diff
@@ -55,17 +55,26 @@ class NpmAddDependencies {
...
+    const [depName, depVersion] = dep.split('@');
     return new Promise((resolve) => {
       npmRun.exec(`npm show ${dep} dist-tags`, (err, stdout) => {
         if (!err) {
           const parsed = stdout.match(/latest: '(.*?)'/i);
 
           if (!parsed || undefined === parsed[1]) {
-            console.error(`Could not obtain the latest version for: ${dep}. Skip.`);
+            if (undefined === depVersion) {
+              console.error(`Could not obtain the latest version for: ${dep}. Skip.`);
```
Comment (arfeo) [inline index.js]: Here can be one `console.log` with the ternary operator inside instead of if...else..., what do you think?

```js
console.error(`Could not obtain the ${depVersion ? 'specified' : 'latest'} version for: ${depName}. Skip.`);
```

File: index.js [hunk 6]
```diff
@@ -55,17 +55,26 @@ class NpmAddDependencies {
...
+            } else {
+              console.error(`Could not obtain the specified version for: ${depName}(${depVersion}). Skip.`);
+            }
           } else {
-            this.result[dep] = `^${parsed[1]}`;
-
-            console.log(`Processed: ${dep}, latest version: ${parsed[1]}`);
+            if (undefined === depVersion) {
+              this.result[dep] = `^${parsed[1]}`;
```
Comment (arfeo) [inline index.js]: We can print `this.result[depName] = ...` here.

File: index.js [hunk 7]
```diff
@@ -55,17 +55,26 @@ class NpmAddDependencies {
...
+              console.log(`Processed: ${dep}, latest version: ${parsed[1]}`);
```
Comment (arfeo) [inline index.js]: We can print `Processed: ${depName}...` here also.

File: index.js [hunk 8]
```diff
@@ -55,17 +55,26 @@ class NpmAddDependencies {
   };
 
   runNpmShow(dep) {
+    const [depName, depVersion] = dep.split('@');
     return new Promise((resolve) => {
```
Comment (arfeo) [inline index.js:101]: Please, add a new line before return.

**Review by arfeo — CHANGES_REQUESTED** [review]

**Comment by 17number** [comment]
Please check below result. `process.argv` removed `"`, so add `"`.

Simple JS and test results.

```js
console.log({args: process.argv});
const dep = process.argv[2];
const [depName, depVersion] = dep.split('@');
const depForShow = undefined === depVersion ? dep : `${depName}@"${depVersion}"`;
console.log({dep: dep, depName: depName, depVersion: depVersion, depForShow: depForShow});
```

```bash
$ node test.js lodash
{
  args: [
    '/Users/r17n/.nodenv/versions/12.7.0/bin/node',
    '/Users/r17n/development/github/npm-add-dependencies/test.js',
    'lodash'
  ]
}
{
  dep: 'lodash',
  depName: 'lodash',
  depVersion: undefined,
  depForShow: 'lodash'
}

$ node test.js lodash@1.2.3
{
  args: [
    '/Users/r17n/.nodenv/versions/12.7.0/bin/node',
    '/Users/r17n/development/github/npm-add-dependencies/test.js',
    'lodash@1.2.3'
  ]
}
{
  dep: 'lodash@1.2.3',
  depName: 'lodash',
  depVersion: '1.2.3',
  depForShow: 'lodash@"1.2.3"'
}

$ node test.js lodash@">=1.0 <2.0"
{
  args: [
    '/Users/r17n/.nodenv/versions/12.7.0/bin/node',
    '/Users/r17n/development/github/npm-add-dependencies/test.js',
    'lodash@>=1.0 <2.0'
  ]
}
{
  dep: 'lodash@>=1.0 <2.0',
  depName: 'lodash',
  depVersion: '>=1.0 <2.0',
  depForShow: 'lodash@">=1.0 <2.0"'
}
```

I checked `npm show locash@"1.0.0"` run normaly.

```bash
$ npm show lodash@"1.0.0" dist-tags
{ latest: '4.17.15' }
```

**Comment by arfeo** [comment]
So, why do you need `depForShow` variable? Since you only need to do this:

```this.result[depName] = `${depVersion}`;```

**Comment by arfeo** [comment]
Wait, I got it.

Try:

```js
npmRun.exec(`npm show ${depName} dist-tags`, (err, stdout) => {
```

**Comment by arfeo** [comment]
I think I got it.

Ok, I think, we should not run `npm show` in case the version is specified by user. We just do

```js
this.result[depName] = `${depVersion}`;
```

What do you think?

The result for `npm show` brings nothing interesting for us:

```bash
$ npm show lodash@">=1.0 <2.0" dist-tags
lodash@1.0.0 { latest: '4.17.15' }
lodash@1.0.1 { latest: '4.17.15' }
lodash@1.1.0 { latest: '4.17.15' }
lodash@1.1.1 { latest: '4.17.15' }
lodash@1.2.0 { latest: '4.17.15' }
lodash@1.2.1 { latest: '4.17.15' }
lodash@1.3.0 { latest: '4.17.15' }
lodash@1.3.1 { latest: '4.17.15' }
lodash@1.0.2 { latest: '4.17.15' }
```

**Comment by 17number** [comment]
I wanna exec `npm show lodash@">=1.0 <2.0"`, with double quote(`"`). But `process.argv` remove `"`, so ``npmRun.exec(`npm show ${dep} dist-tags`, `` will exec `npm show lodash@>=1.0 <2.0 dist-tags` without `"`.

I'm not good at English, so I may confuse you. I'm sorry my slow reply.

**Comment by arfeo** [comment]
I propose to check for `undefined === depVersion` in the very beginning of the promise callback, and if this statement is true, run `npm show`, else -- just init ```this.result[depName] = `${depVersion}`;```.

**Comment by arfeo** [comment]
Or, we always run `npm show` -- just to check, whether the given `depName` is correct or not. But in this case we only need to change the run command to:

```js
`npm show ${depName} dist-tags`
```

**Comment by 17number** [comment]
I think need to check the existence of specified package and version to exclude typo and version input error. Do you mind code simplicity?

**Comment by arfeo** [comment]
Then in case if `depVersion` is defined, you should run:

```npm show ${depName} versions```

and parse the result searching, whether the specified version/versions range exists or not.

**Comment by arfeo** [comment]
Otherwise, `npm show ... dist-tags` makes no sense.

**Comment by arfeo** [comment]
```bash
$ npm show lodash versions
 
[
  '0.1.0',      '0.2.0',      '0.2.1',   '0.2.2',   '0.3.0',
  '0.3.1',      '0.3.2',      '0.4.0',   '0.4.1',   '0.4.2',
  '0.5.0-rc.1', '0.5.0',      '0.5.1',   '0.5.2',   '0.6.0',
  '0.6.1',      '0.7.0',      '0.8.0',   '0.8.1',   '0.8.2',
  '0.9.0',      '0.9.1',      '0.9.2',   '0.10.0',  '1.0.0-rc.1',
  '1.0.0-rc.2', '1.0.0-rc.3', '1.0.0',   '1.0.1',   '1.0.2',
  '1.1.0',      '1.1.1',      '1.2.0',   '1.2.1',   '1.3.0',
  '1.3.1',      '2.0.0',      '2.1.0',   '2.2.0',   '2.2.1',
  '2.3.0',      '2.4.0',      '2.4.1',   '2.4.2',   '3.0.0',
  '3.0.1',      '3.1.0',      '3.2.0',   '3.3.0',   '3.3.1',
  '3.4.0',      '3.5.0',      '3.6.0',   '3.7.0',   '3.8.0',
  '3.9.0',      '3.9.1',      '3.9.2',   '3.9.3',   '3.10.0',
  '3.10.1',     '4.0.0',      '4.0.1',   '4.1.0',   '4.2.0',
  '4.2.1',      '4.3.0',      '4.4.0',   '4.5.0',   '4.5.1',
  '4.6.0',      '4.6.1',      '4.7.0',   '4.8.0',   '4.8.1',
  '4.8.2',      '4.9.0',      '4.10.0',  '4.11.0',  '4.11.1',
  '4.11.2',     '4.12.0',     '4.13.0',  '4.13.1',  '4.14.0',
  '4.14.1',     '4.14.2',     '4.15.0',  '4.16.0',  '4.16.1',
  '4.16.2',     '4.16.3',     '4.16.4',  '4.16.5',  '4.16.6',
  '4.17.0',     '4.17.1',     '4.17.2',  '4.17.3',  '4.17.4',
  '4.17.5',     '4.17.9',     '4.17.10', '4.17.11', '4.17.12',
  '4.17.13',    '4.17.14',    '4.17.15'
]
```

**Comment by 17number** [comment]
OK, I'll try to change the code to parse the result of `npm show xxx versions`. Thanks.

**Comment by 17number** [comment]
I changed the code to use `npm show xxx versions` when specified version.
Please check [this commit](https://github.com/arfeo/npm-add-dependencies/pull/5/commits/5ee6833bd7c82221ccb696a5eebb8a630ec91ae3). I tested run normally, but code might be not beautiful...

Test example.

```bash
$ npm-add-dependencies --dev vue lodash@4.1.0 nuxt@~0.1.0 react@^0.1.2 webpack@">=1.0 <3.1" mocha@10.0 chai@">=5.0 <6.0"
This script adds dependencies (latest versions) into the package.json file without installing them

Adding dependencies to 'devDependencies'...
Processed: nuxt, specified version: ~0.1.0
Processed: vue, latest version: 2.6.10
Processed: lodash, specified version: 4.1.0
Processed: react, specified version: ^0.1.2
Processed: webpack, specified version: >=1.0 <3.1
Could not obtain the specified version for: chai. Skip.
Could not obtain the specified version for: mocha. Skip.
Done.
```

```diff
   "license": "ISC",
   "devDependencies": {
+    "lodash": "4.1.0",
+    "nuxt": "~0.1.0",
+    "react": "^0.1.2",
+    "vue": "^2.6.10",
+    "webpack": ">=1.0 <3.1"
   }
 }
```

**Comment by arfeo** [comment]
Thank you. Now I think we can merge.
