### PR TITLE
merge new dependencies into existing list instead of overwriting them

### LINKED ISSUE #1: dependencies are not added but replaced
## Expected Behavior
I expect `npm-add-dependencies` will add dependencies, but not replace them

## Actual Behavior
when i try to add some packages to the existing package.json, all the packages already listed in the corresponding section (devDependencies) disappear, so newly added packages fully replace old list.

## Steps to Reproduce the Problem

before
```json
{
  "name": "1-end",
  "version": "0.0.1",
  "license": "MIT",
  "scripts": {
    "build": "next build",
    "start": "next start",
    "dev": "next",
    "lint": "eslint components pages lib"
  },
  "dependencies": {
    "@material-ui/core": "^3.3.1",
    "next": "^7.0.2",
    "prop-types": "^15.6.2",
    "react": "^16.6.0",
    "react-dom": "^16.6.0",
    "react-jss": "^8.6.1"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "eslint": "^5.7.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-react": "^7.11.1"
  }
}
```
command
`npm-add-dependencies eslint-config-prettier eslint-plugin-prettier prettier --dev`

after
```json
{
  "name": "1-end",
  "version": "0.0.1",
  "license": "MIT",
  "scripts": {
    "build": "next build",
    "start": "next start",
    "dev": "next",
    "lint": "eslint components pages lib"
  },
  "dependencies": {
    "@material-ui/core": "^3.3.1",
    "next": "^7.0.2",
    "prop-types": "^15.6.2",
    "react": "^16.6.0",
    "react-dom": "^16.6.0",
    "react-jss": "^8.6.1"
  },
  "devDependencies": {
    "eslint-config-prettier": "^3.3.0",
    "eslint-plugin-prettier": "^3.0.0",
    "prettier": "^1.15.3"
  }
}
```

## Specifications

  - Version: 0.1.2, npm 6.4.1
  - Platform: Ubuntu 18.04

### PR DESCRIPTION
**Pull request by YuriGor**
Fixes #1 

## Proposed Changes

  - keep existing dependencies when adding new

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -96,7 +96,7 @@ class NpmAddDependencies {
         return res;
       }, {});
 
-      json[this.getTargetName()] = this.result;
+      json[this.getTargetName()] = Object.assign(json[this.getTargetName()]||{}, this.result);
```
Comment (arfeo) [inline index.js]: What about doing that:
```
this.result = Object.assign(json[this.getTargetName()] || {}, this.result);
```

before sorting dependencies? Smth like:
```
this.result = Object.assign(json[this.getTargetName()] || {}, this.result);

this.result = Object.keys(this.result).sort().reduce((res, key) => {
    res[key] = this.result[key];

    return res;
}, {});

json[this.getTargetName()] = this.result;
```

So, that all dependencies in the list were sorted by alphabet.
